In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python yang digunakan untuk komputasi matriks. Matplotlib merupakan library python untuk presentasi data berupa grafik atau plot......


In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Rembang' 25.0 1500000.0]
 ['Pati' 30.0 3000000.0]
 ['Kudus' 30.0 2000000.0]
 ['Demak' 20.0 1300000.0]
 ['Semarang' 35.0 nan]
 ['Jepara' 23.0 2400000.0]
 ['Pati' nan 2700000.0]
 ['Kudus' 28.0 1650000.0]
 ['Demak' 33.0 1250000.0]
 ['Semarang' 27.0 2200000.0]
 ['Jepara' 35.0 nan]
 ['Rembang' 22.0 1900000.0]
 ['Kudus' 34.0 2100000.0]
 ['Pati' 40.0 4300000.0]
 ['Demak' 37.0 4500000.0]
 ['Semarang' nan 3500000.0]
 ['Jepara' 31.0 nan]
 ['Rembang' 23.0 1450000.0]
 ['Demak' 26.0 2900000.0]
 ['Kudus' 42.0 3800000.0]
 ['Pati' 33.0 2700000.0]
 ['Semarang' nan 4500000.0]
 ['Jepara' 41.0 nan]
 ['Rembang' 36.0 1650000.0]
 ['Jepara' 25.0 1940000.0]
 ['Pati' 22.0 1790000.0]
 ['Rembang' 33.0 3600000.0]
 ['Kudus' nan 4000000.0]
 ['Demak' 41.0 1370000.0]
 ['Semarang' 34.0 1500000.0]]


In [4]:
print(y)

['Kurang Mampu' 'Mampu' 'Mampu' 'Kurang Mampu' 'Mampu' 'Mampu' 'Mampu'
 'Kurang Mampu' 'Kurang Mampu' 'Mampu' 'Mampu' 'Kurang Mampu' 'Mampu'
 'Mampu' 'Mampu' 'Mampu' 'Kurang Mampu' 'Kurang Mampu' 'Mampu' 'Mampu'
 'Mampu' 'Mampu' 'Mampu' 'Kurang Mampu' 'Kurang Mampu' 'Kurang Mampu'
 'Mampu' 'Mampu' 'Kurang Mampu' 'Kurang Mampu']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['Rembang' 25.0 1500000.0]
 ['Pati' 30.0 3000000.0]
 ['Kudus' 30.0 2000000.0]
 ['Demak' 20.0 1300000.0]
 ['Semarang' 35.0 2519230.769230769]
 ['Jepara' 23.0 2400000.0]
 ['Pati' 31.0 2700000.0]
 ['Kudus' 28.0 1650000.0]
 ['Demak' 33.0 1250000.0]
 ['Semarang' 27.0 2200000.0]
 ['Jepara' 35.0 2519230.769230769]
 ['Rembang' 22.0 1900000.0]
 ['Kudus' 34.0 2100000.0]
 ['Pati' 40.0 4300000.0]
 ['Demak' 37.0 4500000.0]
 ['Semarang' 31.0 3500000.0]
 ['Jepara' 31.0 2519230.769230769]
 ['Rembang' 23.0 1450000.0]
 ['Demak' 26.0 2900000.0]
 ['Kudus' 42.0 3800000.0]
 ['Pati' 33.0 2700000.0]
 ['Semarang' 31.0 4500000.0]
 ['Jepara' 41.0 2519230.769230769]
 ['Rembang' 36.0 1650000.0]
 ['Jepara' 25.0 1940000.0]
 ['Pati' 22.0 1790000.0]
 ['Rembang' 33.0 3600000.0]
 ['Kudus' 31.0 4000000.0]
 ['Demak' 41.0 1370000.0]
 ['Semarang' 34.0 1500000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 0.0 0.0 0.0 1.0 0.0 25.0 1500000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 30.0 3000000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 30.0 2000000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 20.0 1300000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 35.0 2519230.769230769]
 [0.0 1.0 0.0 0.0 0.0 0.0 23.0 2400000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 31.0 2700000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 28.0 1650000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 33.0 1250000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 27.0 2200000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 35.0 2519230.769230769]
 [0.0 0.0 0.0 0.0 1.0 0.0 22.0 1900000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 34.0 2100000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 40.0 4300000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 37.0 4500000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 31.0 3500000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 31.0 2519230.769230769]
 [0.0 0.0 0.0 0.0 1.0 0.0 23.0 1450000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 26.0 2900000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 42.0 3800000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 33.0 2700000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 31.0 4500000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 41.0 2519230.769230769]
 [

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 1 0 1 1 1 0 0 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 1 1 0 0]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [12]:
print(x_train)

[[0.0 0.0 0.0 0.0 1.0 0.0 33.0 3600000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 20.0 1300000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 25.0 1940000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 41.0 2519230.769230769]
 [0.0 0.0 0.0 0.0 1.0 0.0 36.0 1650000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 35.0 2519230.769230769]
 [0.0 0.0 1.0 0.0 0.0 0.0 30.0 2000000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 22.0 1790000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 31.0 2700000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 26.0 2900000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 40.0 4300000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 28.0 1650000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 31.0 4000000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 30.0 3000000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 31.0 2519230.769230769]
 [0.0 0.0 0.0 0.0 1.0 0.0 25.0 1500000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 31.0 3500000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 34.0 1500000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 41.0 1370000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 27.0 2200000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 33.0 1250000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 34.0 2100000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 22.0 1900000.0]
 [0.0 1.0 

In [13]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 0.0 23.0 1450000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 31.0 4500000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 35.0 2519230.769230769]
 [0.0 0.0 1.0 0.0 0.0 0.0 42.0 3800000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 37.0 4500000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 33.0 2700000.0]]


In [14]:
print(y_train)

[1 0 0 1 0 1 1 0 1 1 1 0 1 1 0 0 1 0 0 1 0 1 0 1]


In [15]:
print(y_test)

[0 1 1 1 1 1]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 0.0 0.0 -0.447213595499958 2.2360679774997902 -0.447213595499958
  0.45195268784672127 1.5027030233137584]
 [1.0 0.0 0.0 -0.447213595499958 -0.447213595499958 -0.447213595499958
  -1.7862891948227555 -1.2355897383163907]
 [0.0 1.0 0.0 -0.447213595499958 -0.447213595499958 -0.447213595499958
  -0.9254269322575721 -0.473630013341045]
 [0.0 1.0 0.0 -0.447213595499958 -0.447213595499958 -0.447213595499958
  1.8293323079510146 0.21598017044072815]
 [0.0 0.0 0.0 -0.447213595499958 2.2360679774997902 -0.447213595499958
  0.9684700453858313 -0.8188930137204986]
 [0.0 0.0 0.0 -0.447213595499958 -0.447213595499958 2.2360679774997902
  0.7962975928727946 0.21598017044072815]
 [0.0 0.0 1.0 -0.447213595499958 -0.447213595499958 -0.447213595499958
  -0.06456466969238875 -0.4021962891246063]
 [0.0 0.0 0.0 2.2360679774997902 -0.447213595499958 -0.447213595499958
  -1.441944289796682 -0.6522143238821416]
 [0.0 0.0 0.0 2.2360679774997902 -0.447213595499958 -0.447213595499958
  0.10760778282064792 

In [18]:
print(x_test)

[[0.0 0.0 0.0 -0.447213595499958 2.2360679774997902 -0.447213595499958
  -1.2697718372836455 -1.057005427775294]
 [0.0 0.0 0.0 -0.447213595499958 -0.447213595499958 2.2360679774997902
  0.10760778282064792 2.5742088865603385]
 [0.0 1.0 0.0 -0.447213595499958 -0.447213595499958 -0.447213595499958
  0.7962975928727946 0.21598017044072815]
 [0.0 0.0 1.0 -0.447213595499958 -0.447213595499958 -0.447213595499958
  2.0015047604640515 1.740815437368554]
 [1.0 0.0 0.0 -0.447213595499958 -0.447213595499958 -0.447213595499958
  1.1406424978988678 2.5742088865603385]
 [0.0 0.0 0.0 2.2360679774997902 -0.447213595499958 -0.447213595499958
  0.45195268784672127 0.43119716006717823]]
